# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 03:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civiccomments.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
