# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 19:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civiccomments', '0003_auto_20181116_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='authored_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
